apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-channel-provider
spec:
  selector:
    matchLabels:
      name: f-channel-provider
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: f-channel-provider
    spec:
      containers:
        - name: f-channel-provider
          image: harbor.qsbp.io:80/qsbp/f-channel-provider:{{tag}}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 200m
              memory: 200Mi
          ports:
            - containerPort: 80
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            # 保持docker时区与宿主机保持一致
            - name: localtime
              mountPath: /etc/localtime
#            - name: data
#              mountPath: /usr/share/nginx/html/static
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
        # - name: data
        #   persistentVolumeClaim:
        #     claimName: f-channel-provider-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: f-channel-provider-service
spec:
  selector:
    name: f-channel-provider
  type: ClusterIP
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: f-channel-provider-ingress
spec:
  rules:
    - host: qsbp.io
      http:
        paths:
          - path: /channel/f(/|$)(.*)
            backend:
              serviceName: f-channel-provider-service
              servicePort: 80